routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::resources([
  '/classroom' => 'ClassroomController',
  '/student' => 'StudentController',
  '/teacher' => 'TeacherController',
]);

Route::resource('/teacher', 'TeacherController', ['except' => ['destroy']]);
Route::resource('/student', 'StudentController', ['except' => ['destroy']]);
Route::resource('/classroom', 'ClassroomController', ['except' => ['destroy']]);

Auth::routes();

// Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
// Route::post('login', 'Auth\LoginController@login');
// Route::post('logout', 'Auth\LoginController@logout')->name('logout');

Route::get('/home', 'HomeController@index')->name('home');

app/Teacher.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Teacher extends Model
{
    protected $fillable = [
      'teacher_id',
      'nric',
      'name',
      'gender',
      'phone_no',
      'qualification',
      'class_id'
    ];

    public function classrooms(){
      return $this->hasMany(Classroom::class);
    }
}

app/Http/Controllers/TeacherController.php
<?php

namespace App\Http\Controllers;

use App\Teacher;
use Illuminate\Http\Request;

class TeacherController extends Controller
{
    public function __construct(){
      $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $this->authorize('view', Teacher::class);

        $teachers = Teacher::orderBy('name', 'asc')->get();

        return view('teachers.index', [
            'teachers' => $teachers
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $this->authorize('create', Teacher::class);

        $teacher = new Teacher();

        return view('teachers.create', [
            'teacher' => $teacher
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
          'teacher_id' => [
            'required',
            'unique:teachers',
            'regex:/^([A-Z]{1})([0-9]{3})$/'
          ],
          'nric'=>[
            'required',
            'regex:/^([0-9]{2})([0-1]{1})([0-9]{1})([0-3]{1})([0-9]{1})([0-9]{6})$/',
          ],
          'name'=> 'required|max:100',
          'gender' => 'required',
          'phone_no' => [
            'required',
            'regex:/^([0-9]{10})$/'
          ],
          'qualification'=>'required'
        ]);

        $teacher = new Teacher;
        $teacher->fill($request->all());
        $teacher->save();

        return redirect()->route('teacher.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $teacher = Teacher::find($id);
        if(!$teacher) throw new ModelNotFoundException;

        $this->authorize('view', $teacher);

        return view('teachers.show', [
            'teacher'=>$teacher
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $teacher=Teacher::find($id);
        if(!$teacher)throw new ModelNotFoundException;

        $this->authorize('manage', $teacher);

        return view('teachers.edit', [
            'teacher' => $teacher
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
      $request->validate([
        'teacher_id' => [
          'required',
          'regex:/^([A-Z]{1})([0-9]{3})$/'
        ],
        'nric'=>[
          'required',
          'regex:/^([0-9]{2})([0-1]{1})([0-9]{1})([0-3]{1})([0-9]{1})([0-9]{6})$/',
        ],
        'name'=> 'required|max:100',
        'gender' => 'required',
        'phone_no' => [
          'required',
          'regex:/^([0-9]{10})$/'
        ],
        'qualification'=>'required'
      ]);

        $teacher = Teacher::find($id);
        if(!$teacher)throw new ModelNotFoundException;

        $this->authorize('manage', $teacher);

        $teacher->fill($request->all());
        $teacher->save();
        return redirect()->route('teacher.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/teachers/create.blade.php
<?php
  use App\Common;
?>
@extends('layouts.app')
@section('content')

@if ($errors->any())
  <div class="alert alert-danger">
    <ul>
      @foreach($errors->all() as $error)
        <li>{{ $error }}</li>
      @endforeach
    </ul>
  </div>
@endif

  <!-- Bootstrap Boilerplate -->
  <div class="panel-body">
    <!-- New Class Form -->
    {!! Form::model($teacher, [
        'route' => ['teacher.store'],
        'class' => 'form-horizontal'
    ]) !!}

      <!-- Teacher ID -->
      <div class="form-group row">
        {!! Form::label('teacher_id', 'Teacher ID', [
            'class' => 'control-label col-sm-3'
        ]) !!}
        <div class="col-sm-9">
          {!! Form::text('teacher_id', null, [
              'id' => 'teacher_id',
              'class' => 'form-control',
              'maxlength' => 4
          ]) !!}
        </div>
      </div>

      <!-- Teacher NRIC -->
      <div class="form-group row">
        {!! Form::label('teacher_nric', 'Teacher NRIC', [
            'class' => 'control-label col-sm-3'
        ]) !!}
        <div class="col-sm-9">
          {!! Form::text('nric', null, [
              'id' => 'nric',
              'class' => 'form-control',
              'maxlength' => 12
          ]) !!}
        </div>
      </div>

      <!-- Teacher Name -->
      <div class="form-group row">
        {!! Form::label('teacher_name', 'Teacher Name', [
            'class' => 'control-label col-sm-3'
        ]) !!}
        <div class="col-sm-9">
          {!! Form::text('name', null, [
              'id' => 'name',
              'class' => 'form-control',
              'maxlength' => 100
          ]) !!}
        </div>
      </div>

      <!-- Teacher Gender -->
      <div class="form-group row">
        {!! Form::label('teacher_gender', 'Teacher Gender', [
            'class' => 'control-label col-sm-3'
        ]) !!}
        <div class="col-sm-9">
          @foreach(Common::$genders as $key => $val)
            {!! Form::radio('gender', $key) !!} {{$val}}
          @endforeach
        </div>
      </div>

      <!-- Teacher Phone No -->
      <div class="form-group row">
        {!! Form::label('teacher_phone-no', 'Teacher Phone No', [
            'class' => 'control-label col-sm-3'
        ]) !!}
        <div class="col-sm-9">
          {!! Form::text('phone_no', null, [
              'id' => 'phone_no',
              'class' => 'form-control',
              'maxlength' => 10
          ]) !!}
        </div>
      </div>

      <!-- Teacher Qualification -->
      <div class="form-group row">
        {!! Form::label('teacher_qualification', 'Teacher Qualification', [
            'class' => 'control-label col-sm-3'
        ]) !!}
        <div class="col-sm-9">
          {!! Form::select('qualification', Common::$qualifications, null, [
              'class' => 'form-control',
              'placeholder' => '- Select Qualification -'
          ]) !!}
        </div>
      </div>

      <!-- Submit -->
      <div class="form-group row">
        <div class="col-sm-offset-3 col-sm-6">
          {!! Form::button('Save', [
              'type' => 'submit',
              'class' => 'btn btn-primary'
          ]) !!}
        </div>
      </div>

      {!! Form::close() !!}
    </div>
@endsection

resources/views/teachers/edit.blade.php
<?php
  use App\Common;
?>
@extends('layouts.app')
@section('content')

@if ($errors->any())
  <div class="alert alert-danger">
    <ul>
      @foreach($errors->all() as $error)
        <li>{{ $error }}</li>
      @endforeach
    </ul>
  </div>
@endif

  <!-- Bootstrap Boilerplate -->
    <!-- Existing Teacher Form -->
    {!! Form::model($teacher, [
        'route' => ['teacher.update', $teacher->id],
        'method' => 'put',
        'class' => 'form-horizontal'
    ]) !!}
      <!-- Teacher ID -->
      <div class="form-group row">
        {!! Form::label('teacher_id', 'Teacher ID', [
            'class' => 'control-label col-sm-3'
        ]) !!}
        <div class="col-sm-9">
          {!! Form::text('teacher_id', $teacher->teacher_id, [
              'id' => 'teacher_id',
              'class' => 'form-control',
              'maxlength' => 4
          ]) !!}
        </div>
      </div>

      <!-- Teacher NRIC -->
      <div class="form-group row">
        {!! Form::label('teacher_nric', 'Teacher NRIC', [
            'class' => 'control-label col-sm-3'
        ]) !!}
        <div class="col-sm-9">
          {!! Form::text('nric', $teacher->nric, [
              'id' => 'nric',
              'class' => 'form-control',
              'maxlength' => 12
          ]) !!}
        </div>
      </div>

      <!-- Teacher Name -->
      <div class="form-group row">
        {!! Form::label('teacher_name', 'Teacher Name', [
            'class' => 'control-label col-sm-3'
        ]) !!}
        <div class="col-sm-9">
          {!! Form::text('name', $teacher->name, [
              'id' => 'name',
              'class' => 'form-control',
              'maxlength' => 100
          ]) !!}
        </div>
      </div>

      <!-- Teacher Gender -->
      <div class="form-group row">
        {!! Form::label('teacher_gender', 'Teacher Gender', [
            'class' => 'control-label col-sm-3'
        ]) !!}
        <div class="col-sm-9">
          @foreach(Common::$genders as $key => $val)
            {!! Form::radio('gender', $key) !!} {{$val}}
          @endforeach
        </div>
      </div>

      <!-- Teacher Phone No -->
      <div class="form-group row">
        {!! Form::label('teacher_phone_no', 'Teacher Phone No', [
            'class' => 'control-label col-sm-3'
        ]) !!}
        <div class="col-sm-9">
          {!! Form::text('phone_no', $teacher->phone_no, [
              'id' => 'phone_no',
              'class' => 'form-control',
              'maxlength' => 10
          ]) !!}
        </div>
      </div>

      <!-- Teacher Qualification -->
      <div class="form-group row">
        {!! Form::label('teacher_qualification', 'Teacher Qualification', [
            'class' => 'control-label col-sm-3'
        ]) !!}
        <div class="col-sm-9">
          {!! Form::select('qualification', Common::$qualifications, $teacher->qualification, [
              'class' => 'form-control',
              'placeholder' => '- Select Qualification -'
          ]) !!}
        </div>
      </div>

      <!-- Submit -->
      <div class="form-group row">
        <div class="col-sm-offset-3 col-sm-6">
          {!! Form::button('Update', [
              'type' => 'submit',
              'class' => 'btn btn-primary'
          ]) !!}
        </div>
      </div>

      {!! Form::close() !!}
    </div>
@endsection

resources/views/teachers/index.blade.php
<?php
  use App\Common;
?>
@extends('layouts.app')
@section('content')

  <!-- Bootstrap Boilerplate -->
  <div class="panel-body">
    @if (count($teachers) >0)
    <table class="table table-striped task-table">
      <!-- Table Headings -->
      <thead>
        <tr>
          <th>No.</th>
          <th>Teacher ID</th>
          <th>Teacher NRIC</th>
          <th>Teacher Name</th>
          <th>Teacher Gender</th>
          <th>Teacher Phone No</th>
          <th>Teacher Qualification</th>
          <th>Created At</th>
          <th>Updated At</th>
        </tr>
      </thead>
      <!-- Table Body -->
      <tbody>
        @foreach($teachers as $i => $teacher)
        <tr>
          <td class="table-text">
            <div>{{ $i+1 }}</div>
          </td>
          <td class="table-text">
            <div>{!! link_to_route(
                    'teacher.show',
                    $title = $teacher->teacher_id,
                    $parameters = [
                      'id' => $teacher->id,
                    ]
              ) !!}
            </div>
          </td>
          <td class="table-text">
            <div>{{ $teacher->nric }}</div>
          </td>
          <td class="table-text">
            <div>{{ $teacher->name }}</div>
          </td>
          <td class="table-text">
            <div>{{ Common::$genders[$teacher->gender] }}</div>
          </td>
          <td class="table-text">
            <div>{{ $teacher->phone_no }}</div>
          </td>
          <td class="table-text">
            <div>{{ Common::$qualifications[$teacher->qualification] }}</div>
          </td>
          <td class="table-text">
            <div>{{ $teacher->created_at }}</div>
          </td>
          <td class="table-text">
            <div>{{ $teacher->updated_at }}</div>
          </td>
          <td class="table-text">
            <div>{!! link_to_route(
                      'teacher.edit',
                      $title = 'Edit',
                      $parameters = [
                          'id' => $teacher->id,
                      ]
              ) !!}
            </div>
          </td>
        </tr>
      @endforeach
      </tbody>
    </table>
  @else
    <div>
      <tbody>
        <h1>No records found</h1>
      </tbody>
    </div>
  @endif

  <!-- Create New Classroom button -->
  <div class="form-group row">
    <div class="col-sm-offset-3 col-sm-6">
      <a href="{{ route('teacher.create') }}" type='Button' class='btn btn-primary'>Insert New Teacher</a>
    </div>
  </div>

  </div>
@endsection

resources/views/teachers/show.blade.php
<?php
  use App\Common;
?>
@extends('layouts.app')
@section('content')

  <!-- Bootstrap Boilerplate -->
  <div class="panel-body">
    <table class="table table-striped task-table">
      <!-- Table Headings -->
      <thead>
        <tr>
          <th>Attribute</th>
          <th>Value</th>
        </tr>
      </thead>
      <!-- Table Body -->
      <tbody>
        <tr>
          <td>Teacher ID</td>
          <td>{{ $teacher->teacher_id }}</td>
        </tr>
        <tr>
          <td>Teacher NRIC</td>
          <td>{{ $teacher->nric }}</td>
        </tr>
        <tr>
          <td>Teacher Name</td>
          <td>{{ $teacher->name }}</td>
        </tr>
        <tr>
          <td>Teacher Gender</td>
          <td>{{ Common::$genders[$teacher->gender] }}</td>
        </tr>
        <tr>
          <td>Teacher Phone No</td>
          <td>{{ $teacher->phone_no }}</td>
        </tr>
        <tr>
          <td>Teacher Qualification</td>
          <td>{{ Common::$qualifications[$teacher->qualification] }}</td>
        </tr>
      </tbody>
    </table>
  </div>
@endsection