routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::resources([
  '/classroom' => 'ClassroomController',
  '/student' => 'StudentController',
  '/teacher' => 'TeacherController',
]);

Route::resource('/teacher', 'TeacherController', ['except' => ['destroy']]);
Route::resource('/student', 'StudentController', ['except' => ['destroy']]);
Route::resource('/classroom', 'ClassroomController', ['except' => ['destroy']]);

Auth::routes();

// Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
// Route::post('login', 'Auth\LoginController@login');
// Route::post('logout', 'Auth\LoginController@logout')->name('logout');

Route::get('/home', 'HomeController@index')->name('home');

app/Student.php
<?php

namespace App;

use App\Student;
use Illuminate\Database\Eloquent\Model;

class Student extends Model
{
    protected $fillable = [
      'student_id',
      'nric',
      'name',
      'gender',
      'address',
      'postcode',
      'city',
      'state',
      'guardian',
      'guardian_phone_no',
      'classroom_id'
    ];

    public function classrooms(){
      return $this->belongsToMany('App\Classroom', 'classrooms_students')->withPivot('classroom_id');
    }

}

app/Http/Controllers/StudentController.php
<?php

namespace App\Http\Controllers;

use App\Student;
use App\Classroom;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class StudentController extends Controller
{
    public function __construct(){
      $this->middleware('auth');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $this->authorize('view', Student::class);

        $students = Student::orderBy('nric', 'asc')->get();

        return view('students.index', [
            'students' => $students
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $this->authorize('create', Student::class);

        $student = new Student();

        return view('students.create', [
            'student' => $student,
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
          'student_id' => [
            'required',
            'unique:students',
            'regex:/^([1-9]{2})([0-9]{3})$/'
          ],
          'nric' => [
            'required',
            'regex:/^([0-9]{2})([0-1]{1})([0-9]{1})([0-3]{1})([0-9]{1})([0-9]{6})$/'
          ],
          'name' => 'required|max:100',
          'gender' => 'required',
          'address' => 'required|max:500',
          'postcode' => [
            'required',
            'regex:/^([0-9]{5})$/'
          ],
          'city' => 'required|max:50',
          'state' => 'required',
          'guardian' => 'required|max:100',
          'guardian_phone_no' => [
            'required',
            'regex:/^([0-9]{10})$/'
          ]
        ]);

        $student = new Student;
        $student->fill($request->except('classroom_id'));
        $student->save();
        $student->fill($request->all());
        $student->classrooms()->attach($student->classroom_id);

        return redirect()->route('student.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $student = Student::find($id);
        if(!$student) throw new ModelNotFoundException;

        $this->authorize('view', $student);

        return view('students.show', [
            'student' => $student
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $student = Student::find($id);
        if(!$student) throw new ModelNotFoundException;

        $this->authorize('manage', $student);

        return view('students.edit', [
          'student' => $student
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
          'student_id' => [
            'required',
            'regex:/^([1-9]{2})([0-9]{3})$/'
          ],
          'nric' => [
            'required',
            'regex:/^([0-9]{2})([0-1]{1})([0-9]{1})([0-3]{1})([0-9]{1})([0-9]{6})$/'
          ],
          'name' => 'required|max:100',
          'gender' => 'required',
          'address' => 'required|max:500',
          'postcode' => [
            'required',
            'regex:/^([0-9]{5})$/'
          ],
          'city' => 'required|max:50',
          'state' => 'required',
          'guardian' => 'required|max:100',
          'guardian_phone_no' => [
            'required',
            'regex:/^([0-9]{10})$/'
          ]
        ]);

        $student = Student::find($id);
        if(!$student) throw new ModelNotFoundException;

        $this->authorize('manage', $student);

        $student->fill($request->except('classroom_id'));
        $student->save();
        $student->fill($request->all());
        $student->classrooms()->sync($student->classroom_id);
        return redirect()->route('student.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/students/create.blade.php
<?php
  use App\Common;
  use App\Classroom;
?>
@extends('layouts.app')
@section('content')

@if ($errors->any())
  <div class="alert alert-danger">
    <ul>
      @foreach($errors->all() as $error)
        <li>{{ $error }}</li>
      @endforeach
    </ul>
  </div>
@endif

  <!-- Bootstrap Boilerplate -->
  <div class="panel-body">
    <!-- New Student Form -->
    {!! Form::model($student, [
        'route' => ['student.store'],
        'class' => 'form-horizontal',
    ]) !!}

      <!-- Student ID -->
      <div class="form-group row">
        {!! Form::label('student_id', 'Student ID', [
          'class' => 'control-label col-sm-3',
        ]) !!}
        <div class="col-sm-9">
          {!! Form::text('student_id', null, [
              'id' => 'student_id',
              'class' => 'form-control',
              'maxlength' => 5,
          ]) !!}
        </div>
      </div>

      <!-- Student NRIC -->
      <div class="form-group row">
        {!! Form::label('student_nric', 'Student NRIC', [
          'class' => 'control-label col-sm-3',
        ]) !!}
        <div class="col-sm-9">
          {!! Form::text('nric', null, [
              'id' => 'nric',
              'class' => 'form-control',
              'maxlength'=> 12,
          ]) !!}
        </div>
      </div>

      <!-- Student Name -->
      <div class="form-group row">
        {!! Form::label('student_name', 'Student Name', [
          'class' => 'control-label col-sm-3',
        ]) !!}
        <div class="col-sm-9">
          {!! Form::text('name', null, [
              'id' => 'name',
              'class' => 'form-control',
              'maxlength' => 100,
          ]) !!}
        </div>
      </div>

      <!-- Student Gender -->
      <div class="form-group row">
        {!! Form::label('student_gender', 'Gender', [
            'class' => 'control-label col-sm-3',
        ]) !!}
        <div class="col-sm-9">
          @foreach(Common::$genders as $key => $val)
            {!! Form::radio('gender', $key) !!} {{$val}}
          @endforeach
        </div>
      </div>

      <!-- Student Address -->
      <div class="form-group row">
        {!! Form::label('student_address', 'Address', [
            'class' => 'control-label col-sm-3',
        ]) !!}
        <div class="col-sm-9">
          {!! Form::textarea('address', null, [
              'id' => 'address',
              'class' => 'form-control',
          ]) !!}
        </div>
      </div>

      <!-- Student Postcode -->
      <div class="form-group row">
        {!! Form::label('student_postcode', 'Postcode', [
          'class' => 'control-label col-sm-3',
        ]) !!}
        <div class="col-sm-9">
          {!! Form::text('postcode', null, [
              'id' => 'postcode',
              'class' => 'form-control',
              'maxlength' => 5,
          ]) !!}
        </div>
      </div>

      <!-- Student City -->
      <div class="form-group row">
        {!! Form::label('student_city', 'City', [
            'class' => 'control-label col-sm-3',
        ]) !!}
        <div class="col-sm-9">
          {!! Form::text('city', null, [
              'id' => 'city',
              'class' => 'form-control',
              'maxlength' => 50,
          ]) !!}
        </div>
      </div>

      <!-- Student State -->
      <div class="form-group row">
        {!! Form::label('student_state', 'State', [
            'class' => 'control-label col-sm-3',
        ]) !!}
        <div class="col-sm-9">
          {!! Form::select('state', Common::$states, null, [
              'class' => 'form-control',
              'placeholder' => '- Select State -',
          ]) !!}
        </div>
      </div>

      <!-- Student Guardian -->
      <div class="form-group row">
        {!! Form::label('student_guardian', 'Guardian', [
            'class' => 'control-label col-sm-3',
        ]) !!}
        <div class="col-sm-9">
          {!! Form::text('guardian', null, [
              'id' => 'guardian',
              'class' => 'form-control',
              'maxlength' => 100,
          ]) !!}
        </div>
      </div>

      <!-- Student Guardian Phone No -->
      <div class="form-group row">
        {!! Form::label('student_guardian_phone_no', 'Guardian Phone No', [
            'class' => 'control-label col-sm-3',
        ]) !!}
        <div class="col-sm-9">
          {!! Form::text('guardian_phone_no', null, [
              'id' => 'guaridan_phone_no',
              'class' => 'form-control',
              'maxlength' => 10.
          ]) !!}
        </div>
      </div>

      <!-- Subject taken by students -->
      <div class="form-group row">
        {!! Form::label('subject_taken_by_student', 'Subject Taken', [
            'class' => 'control-label col-sm-3',
        ]) !!}
        <div class="col-sm-9">
          @foreach(Classroom::pluck('name', 'id') as $key => $val)
            {!! Form::checkbox('classroom_id[]', $key) !!}
            {{ $val }}
          @endforeach
        </div>
      </div>

      <!-- Submit Button -->
      <div class="form-group row">
        <div class="col-sm-offset-3 col-sm-6">
          {!! Form::button('Save', [
              'type' => 'submit',
              'class' => 'btn btn-primary',
          ]) !!}
        </div>
      </div>
    {!! Form::close() !!}
  </div>
@endsection

resources/views/students/edit.blade.php
<?php
  use App\Common;
  use App\Student;
  use App\Classroom;
?>
@extends('layouts.app')
@section('content')

@if ($errors->any())
  <div class="alert alert-danger">
    <ul>
      @foreach($errors->all() as $error)
        <li>{{ $error }}</li>
      @endforeach
    </ul>
  </div>
@endif

  <!-- Bootstrap Boilerplate -->
    <!-- Existing Student Form -->
    {!! Form::model($student, [
        'route' => [ 'student.update', $student->id ],
        'method' => 'put',
        'class' => 'form-horizontal'
    ]) !!}
      <!-- Student ID -->
      <div class="form-group row">
        {!! Form::label('student_id', 'Student ID', [
            'class' => 'control-label col-sm-3'
        ]) !!}
        <div class="col-sm-9">
          {!! Form::text('student_id', $student->student_id, [
              'id' => 'student_id',
              'class' => 'form-control',
              'maxlength' => 5
          ]) !!}
        </div>
      </div>

      <!-- NRIC -->
      <div class="form-group row">
        {!! Form::label('student_nric', 'Student NRIC', [
            'class' => 'control-label col-sm-3'
        ]) !!}
        <div class="col-sm-9">
          {!! Form::text('nric', $student->nric, [
              'id' => 'nric',
              'class' => 'form-control',
              'maxlength' => 12
          ]) !!}
        </div>
      </div>

      <!-- Name -->
      <div class="form-group row">
        {!! Form::label('student_name', 'Student Name', [
            'class' => 'control-label col-sm-3'
        ]) !!}
        <div class="col-sm-9">
          {!! Form::text('name', $student->name, [
              'id' => 'name',
              'class' => 'form-control',
              'maxlength' => 100
          ]) !!}
        </div>
      </div>

      <!-- Gender -->
      <div class="form-group row">
        {!! Form::label('student_gender', 'Student Gender', [
            'class' => 'control-label col-sm-3'
        ]) !!}
        <div class="col-sm-9">
          @foreach(Common::$genders as $key => $val)
              {!! Form::radio('gender', $key) !!} {{$val}}
          @endforeach
        </div>
      </div>

      <!-- Address -->
      <div class="form-group row">
        {!! Form::label('student_address', 'Student Address', [
            'class' => 'control-label col-sm-3'
        ]) !!}
        <div class="col-sm-9">
          {!! Form::textarea('address', $student->address, [
              'id' => 'address',
              'class' => 'form-control'
          ]) !!}
        </div>
      </div>

      <!-- Postcode -->
      <div class="form-group row">
        {!! Form::label('student_postcode', 'Postcode', [
            'class' => 'control-label col-sm-3'
        ]) !!}
        <div class="col-sm-9">
          {!! Form::text('postcode', $student->postcode, [
              'id' => 'postcode',
              'class' => 'form-control',
              'maxlength' => 5
          ]) !!}
        </div>
      </div>

      <!-- City -->
      <div class="form-group row">
        {!! Form::label('student_city', 'City', [
            'class' => 'control-label col-sm-3'
        ]) !!}
        <div class="col-sm-9">
          {!! Form::text('city', $student->city, [
              'id' => 'city',
              'class' => 'form-control',
              'maxlength' => 50
          ]) !!}
        </div>
      </div>

      <!-- state -->
      <div class="form-group row">
        {!! Form::label('student_state', 'State', [
            'class' => 'control-label col-sm-3'
        ]) !!}
        <div class="col-sm-9">
          {!! Form::select('state', Common::$states, $student->state, [
              'class' => 'form-control',
              'placeholder' => '- Select State -'
          ]) !!}
        </div>
      </div>

      <!-- guardian -->
      <div class="form-group row">
        {!! Form::label('student_guardian', 'Guardian Name', [
            'class' => 'control-label col-sm-3'
        ]) !!}
        <div class="col-sm-9">
          {!! Form::text('guardian', $student -> guardian, [
              'id' => 'guardian',
              'class' => 'form-control',
              'maxlength' => 100
          ]) !!}
        </div>
      </div>

      <!-- guardian phone no -->
      <div class="form-group row">
        {!! Form::label('student_phone_no', 'Guardian Phone No', [
            'class' => 'control-label col-sm-3'
        ]) !!}
        <div class="col-sm-9">
          {!! Form::text('guardian_phone_no', $student -> guardian_phone_no, [
              'id' => 'guardian_phone_no',
              'class' => 'form-control',
              'maxlength' => 10,
          ]) !!}
        </div>
      </div>

      <!-- Subject taken by students -->
      <div class="form-group row">
        {!! Form::label('subject_taken_by_student', 'Subject Taken', [
            'class' => 'control-label col-sm-3',
        ]) !!}
        <div class="col-sm-9">
          @foreach(Classroom::pluck('name', 'id') as $key => $val)
            {!! Form::checkbox('classroom_id[]', $key) !!}
            {{ $val }}
          @endforeach
        </div>
      </div>

      <!-- submit -->
      <div class="form-group row">
        <div class="col-sm-offset-3 col-sm-6">
          {!! Form::button('Update', [
              'type' => 'submit',
              'class' => 'btn btn-primary'
          ]) !!}
        </div>
      </div>

    {!! Form::close() !!}
  </div>

@endsection

resources/views/students/index.blade.php
<?php
  use App\Common;
  use App\Classroom;
?>
@extends('layouts.app')
@section('content')

  <!-- Bootstrap Boilerplate -->
  <div class="panel-body">
    @if (count($students) > 0)
      <table class="table table-striped task-table">
        <!-- Table Headings -->
        <thead>
          <tr>
            <th>No.</th>
            <th>Student ID</th>
            <th>NRIC</th>
            <th>Name</th>
            <th>Gender</th>
            <th>Address</th>
            <th>Postcode</th>
            <th>City</th>
            <th>State</th>
            <th>Guardian</th>
            <th>Guardian Phone No</th>
            <th>Classes Taken</th>
            <th>Created At</th>
            <th>Updated At</th>
          </th>
        </thead>

        <!-- Table Body -->
        <tbody>
          @foreach ($students as $i => $student)
            <tr>
              <td class="table-text">
                <div>{{ $i+1 }}</div>
              </td>
              <td class="table-text">
                <div>{!! link_to_route(
                            'student.show',
                            $title = $student->student_id,
                            $parameters = [
                              'id' => $student->id,
                            ]
                     ) !!}
                </div>
              </td>
              <td class="table-text">
                <div>{{ $student->nric }}</div>
              </td>
              <td class="table-text">
                <div>{{ $student->name }}</div>
              </td>
              <td class="table-text">
                <div>{{ Common::$genders[$student->gender] }}</div>
              </td>
              <td class="table-text">
                <div>{{ $student->address }}</div>
              </td>
              <td class="table-text">
                <div>{{ $student->postcode }}</div>
              </td>
              <td class="table-text">
                <div>{{ $student->city }}</div>
              </td>
              <td class="table-text">
                <div>{{ Common::$states[$student->state] }}</div>
              </td>
              <td class="table-text">
                <div>{{ $student->guardian }}</div>
              </td>
              <td class="table-text">
                <div>{{ $student->guardian_phone_no }}</div>
              </td>
              <td class="table-text">
                @foreach($student->classrooms as $classroom)
                    <div>{{ $classroom->pivot->classroom_id }}</div>
                @endforeach
              </td>
              <td class="table-text">
                <div>{{ $student->created_at }}</div>
              </td>
              <td class="table-text">
                <div>{{ $student->updated_at }}</div>
              </td>
              <td class="table-text">
                <div>{!! link_to_route(
                            'student.edit',
                            $title = 'Edit',
                            $parameters = [
                                'id' => $student->id,
                            ]
                     ) !!}
                </div>
              </td>
            </tr>
            @endforeach
          </tbody>
        </table>
    @else
        <div>
          <tbody>
            <h1>No records found</h1>
          </tbody>
        </div>
    @endif

    <!-- Create New Student button -->
    <div class="form-group row">
      <div class="col-sm-offset-3 col-sm-6">
        <a href="{{ route('student.create') }}" type='Button' class='btn btn-primary'>Insert New Student</a>
      </div>
    </div>

  </div>
@endsection

resources/views/students/show.blade.php
<?php
    use App\Common;
?>
@extends('layouts.app')
@section('content')

  <!-- Bootstrap Boilerplate -->
  <div class="panel-body">
    <table class="table table-striped task-table">
      <!-- Table Headings -->
      <thead>
        <tr>
          <th>Attribute</th>
          <th>Value</th>
        </tr>
      </thead>
      <!-- Table Body -->
      <tbody>
        <tr>
          <td>Student ID</td>
          <td>{{ $student->student_id }}</td>
        </tr>
        <tr>
          <td>Student NRIC</td>
          <td>{{ $student->nric }}</td>
        </tr>
        <tr>
          <td>Student Name</td>
          <td>{{ $student->name }}</td>
        </tr>
        <tr>
          <td>Student Gender</td>
          <td>{{ Common::$genders[$student->gender] }}</td>
        </tr>
        <tr>
          <td>Student Address</td>
          <td>{!!  nl2br($student->address) !!}</td>
        </tr>
        <tr>
          <td>Postcode</td>
          <td>{{ $student->postcode }}</td>
        </tr>
        <tr>
          <td>City</td>
          <td>{{ $student->city }}</td>
        </tr>
        <tr>
          <td>State</td>
          <td>{{ Common::$states[$student->state] }}</td>
        </tr>
        <tr>
          <td>Guardian Name</td>
          <td>{{ $student->guardian }}</td>
        </tr>
        <tr>
          <td>Guardian Phone No</td>
          <td>{{ $student->id }}</td>
        </tr>
        <tr>
          <td>Classes Taken</td>
          @foreach($student->classrooms as $classroom)
              <td>{{ $classroom->pivot->classroom_id }}</td>
          @endforeach
        </tr>
      </tbody>
    </table>
  </div>

@endsection