routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::resources([
  '/classroom' => 'ClassroomController',
  '/student' => 'StudentController',
  '/teacher' => 'TeacherController',
]);

Route::resource('/teacher', 'TeacherController', ['except' => ['destroy']]);
Route::resource('/student', 'StudentController', ['except' => ['destroy']]);
Route::resource('/classroom', 'ClassroomController', ['except' => ['destroy']]);

Auth::routes();

// Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
// Route::post('login', 'Auth\LoginController@login');
// Route::post('logout', 'Auth\LoginController@logout')->name('logout');

Route::get('/home', 'HomeController@index')->name('home');

app/Classroom.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Classroom extends Model
{
    protected $fillable = [
      'class_code',
      'name',
      'description',
      'room',
      'teacher_id'
    ];

    //protected $touches = ['teacher', 'student'];

    public function teacher(){
      return $this->belongsTo(Teacher::class);
    }

    public function students(){
      return $this->belongsToMany(Student::class, 'classrooms_students');
    }
}

app/Http/Controllers/ClassroomController.php
<?php

namespace App\Http\Controllers;

use App\Classroom;
use App\Student;
use Illuminate\Http\Request;

class ClassroomController extends Controller
{
    public function __construct(){
      $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $this->authorize('view', Classroom::class);

        $classroom = Classroom::orderBy('class_code', 'asc')->get();

        return view('classrooms.index', [
            'classroom' => $classroom
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
      $this->authorize('create', Classroom::class);

      $classroom = new Classroom();

      return view('classrooms.create', [
          'classroom' => $classroom,
      ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
      $request->validate([
        'class_code' => [
          'required',
          'unique:classrooms',
          'regex:/^([0-9,A-Z]{4})$/'
        ],
        'name' => 'required|max:50',
        'description' => 'required|max:150',
        'room' => 'required',
        'teacher_id' => 'required'
      ]);

        $class = new Classroom();
        $class->fill($request->all());
        $class->save();

        return redirect()->route('classroom.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $classroom = Classroom::find($id);
        if(!$classroom)throw new ModelNotFoundException;

        $this->authorize('view', $classroom);

        return view('classrooms.show', [
            'classroom' => $classroom
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $classroom = Classroom::find($id);
        if(!$classroom) throw new ModelNotFoundException;

        $this->authorize('manage', $classroom);

        return view('classrooms.edit', [
            'classroom' => $classroom
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
      $request->validate([
        'class_code' => [
          'required',
          'regex:/^([0-9,A-Z]{4})$/'
        ],
        'name' => 'required|max:50',
        'description' => 'required|max:150',
        'room' => 'required',
        'teacher_id' => 'required'
      ]);

        $classroom = Classroom::find($id);
        if(!$classroom) throw new ModelNotFoundException;

        $this->authorize('manage', $classroom);

        $classroom->fill($request->all());
        $classroom->save();
        return redirect()->route('classroom.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/classrooms/create.blade.php
<?php
  use App\Common;
  use App\Teacher;
?>
@extends('layouts.app')
@section('content')

@if ($errors->any())
  <div class="alert alert-danger">
    <ul>
      @foreach($errors->all() as $error)
        <li>{{ $error }}</li>
      @endforeach
    </ul>
  </div>
@endif

  <!-- Bootstrap Boilerplate -->
  <div class="panel-body">
    <!-- New Class Form -->
    {!! Form::model($classroom, [
        'route' => ['classroom.store'],
        'class' => 'form-horizontal'
    ]) !!}

      <!-- Class Code -->
      <div class="form-group row">
        {!! Form::label('class_code', 'Class Code', [
            'class' => 'control-label col-sm-3'
        ]) !!}
        <div class="col-sm-9">
          {!! Form::text('class_code', null, [
              'id' => 'class_code',
              'class' => 'form-control',
              'maxlength' => 4,
          ]) !!}
        </div>
      </div>

      <!-- Class Name -->
      <div class="form-group row">
        {!! Form::label('class_name', 'Class Name', [
            'class' => 'control-label col-sm-3'
        ]) !!}
        <div class="col-sm-9">
          {!! Form::text('name', null, [
              'id' => 'name',
              'class' => 'form-control',
              'maxlength' => 5,
          ]) !!}
        </div>
      </div>

      <!-- Class Description -->
      <div class="form-group row">
        {!! Form::label('class_description', 'Class Description', [
            'class' => 'control-label col-sm-3'
        ]) !!}
        <div class="col-sm-9">
          {!! Form::textarea('description', null, [
              'id' => 'description',
              'class' => 'form-control'
          ]) !!}
        </div>
      </div>

      <!-- Class Room -->
      <div class="form-group row">
        {!! Form::label('class_room', 'Class Room', [
            'class' => 'control-label col-sm-3'
        ]) !!}
        <div class="col-sm-9">
          {!! Form::select('room', Common::$rooms, null, [
              'class' => 'form-control',
              'placeholder' => '- Select Room -'
          ]) !!}
        </div>
      </div>

      <!-- Class Teacher -->
      <div class="form-group row">
        {!! Form::label('class_teacher_id', 'Teacher In Charge', [
            'class' => 'control-label col-sm-3'
        ]) !!}
        <div class="col-sm-9">
          {!! Form::select('teacher_id',
              Teacher::pluck('name', 'id'), null, [
                'class' => 'form-control',
                'placeholder' => '- Select Teacher -'
          ]) !!}
        </div>
      </div>

      <!-- Submit Button -->
      <div class="form-group row">
        <div class="col-sm-offset-3 col-sm-6">
          {!! Form::button('Save', [
            'type' => 'submit',
            'class' => 'btn btn-primary'
          ]) !!}
        </div>
      </div>
      {!! Form::close() !!}
  </div>
@endsection

resources/views/classrooms/edit.blade.php
<?php
  use App\Common;
  use App\Teacher;
  use App\Classroom;
?>
@extends('layouts.app')
@section('content')

@if ($errors->any())
  <div class="alert alert-danger">
    <ul>
      @foreach($errors->all() as $error)
        <li>{{ $error }}</li>
      @endforeach
    </ul>
  </div>
@endif

  <!-- Bootstrap Boilerplate -->
    <!-- Existing Classroom Form -->
    {!! Form::model($classroom, [
        'route' => [ 'classroom.update', $classroom->id ],
        'method' => 'put',
        'class' => 'form-horizontal'
    ]) !!}
      <!-- Classroom Code -->
      <div class="form-group row">
        {!! Form::label('classroom_code', 'Classroom Code', [
            'class' => 'control-label col-sm-3'
        ]) !!}
        <div class="col-sm-9">
          {!! Form::text('class_code', $classroom->class_code, [
              'id' => 'class_code',
              'class' => 'form-control',
              'maxlength' => 4
          ]) !!}
        </div>
      </div>

      <!-- name -->
      <div class="form-group row">
        {!! Form::label('classroom_name', 'Classroom Name', [
            'class' => 'control-label col-sm-3'
        ]) !!}
        <div class="col-sm-9">
          {!! Form::text('name', $classroom->name, [
              'id' => 'name',
              'class' => 'form-control',
              'maxlength' => 50
          ]) !!}
        </div>
      </div>

      <!-- description -->
      <div class="form-group row">
        {!! Form::label('classroom_description', 'Classroom Description', [
            'class' => 'control-label col-sm-3'
        ]) !!}
        <div class="col-sm-9">
          {!! Form::textarea('description', $classroom->description, [
              'id' => 'description',
              'class' => 'form-control'
          ]) !!}
        </div>
      </div>

      <!-- room -->
      <div class="form-group row">
        {!! Form::label('classroom_room', 'Room', [
            'class' => 'control-label col-sm-3'
        ]) !!}
        <div class="col-sm-9">
          {!! Form::select('room', Common::$rooms, $classroom->room, [
              'class' => 'form-control',
              'placeholder' => '- Select room -'
          ]) !!}
        </div>
      </div>

      <!-- Class Teacher -->
      <div class="form-group row">
        {!! Form::label('class_teacher_id', 'Teacher In Charge', [
            'class' => 'control-label col-sm-3'
        ]) !!}
        <div class="col-sm-9">
          {!! Form::select('teacher_id',
              Teacher::pluck('name', 'id'), null, [
                'class' => 'form-control',
                'placeholder' => '- Select Teacher -'
          ]) !!}
        </div>
      </div>

      <!-- Submit -->
      <div class="form-group row">
        <div class="col-sm-offset-3 col-sm-6">
          {!! Form::button('Update', [
              'type' => 'submit',
              'class' => 'btn btn-primary'
          ]) !!}
        </div>
      </div>

    {!! Form::close() !!}
  </div>

@endsection

resources/views/classrooms/index.blade.php
<?php
  use App\Common;
  use App\Teacher;
?>
@extends('layouts.app')
@section('content')

  <!-- Bootstrap Boilerplate -->
  <div class="panel-body">
    @if (count($classroom) >0 )
      <table class="table table-striped task-table">
        <!-- Table Headings -->
        <thead>
          <tr>
            <th>No.</th>
            <th>Class Code</th>
            <th>Class Name</th>
            <th>Class Description</th>
            <th>Class Room</th>
            <th>Teacher In Charge</th>
            <th>Created At</th>
            <th>Updated At</th>
          </tr>
        </thead>

        <!-- Table Body -->
        <tbody>
          @foreach($classroom as $i => $classroom)
            <tr>
              <td class="table-text">
                <div>{{ $i+1 }}</div>
              </td>
              <td class="table-text">
                <div>{!! link_to_route(
                          'classroom.show',
                          $title = $classroom->class_code,
                          $parameters = [
                            'id' => $classroom->id,
                          ]
                  ) !!}
                </div>
              </td>
              <td class="table-text">
                <div>{{ $classroom->name }}</div>
              </td>
              <td class="table-text">
                <div>{{ $classroom->description }}</div>
              </td>
              <td class="table-text">
                <div>{{ Common::$rooms[$classroom->room] }}</div>
              </td>
              <td class="table-text">
                <div>{!! link_to_route(
                          'teacher.show',
                          $title = $classroom->teacher->name,
                          $parameters = [
                              'id' => $classroom->teacher_id,
                          ]
                      ) !!}
                </div>
              </td>
              <td class="table-text">
                <div>{{ $classroom->created_at }}</div>
              </td>
              <td class="table-text">
                <div>{{ $classroom->updated_at }}</div>
              </td>
              <td class="table-text">
                <div>{!! link_to_route(
                          'classroom.edit',
                          $title = 'Edit',
                          $parameters = [
                              'id' => $classroom->id,
                          ]
                  ) !!}
                </div>
              </td>
            </tr>
            @endforeach
          </tbody>
        </table>
      @else
        <div>
          <tbody>
            <h1>No records found</h1>
          </tbody>
        </div>
      @endif

      <!-- Create New Classroom button -->
      <div class="form-group row">
        <div class="col-sm-offset-3 col-sm-6">
          <a href="{{ route('classroom.create') }}" type='Button' class='btn btn-primary'>Create New Classroom</a>
        </div>
      </div>

    </div>
@endsection

resources/views/classrooms/show.blade.php
<?php
  use App\Common;
  use App\Teacher;
?>
@extends('layouts.app')
@section('content')
  <!-- Bootstrap Boilerplate -->
  <div class="panel-body">
    <table class="table table-striped task-table">
      <!-- Table Headings -->
      <thead>
        <tr>
          <th>Attribute</th>
          <th>Value</th>
        </tr>
      </thead>
      <!-- Table Body -->
      <tbody>
        <tr>
          <td>Class Code</td>
          <td>{{ $classroom->class_code }}</td>
        </tr>
        <tr>
          <td>Class Name</td>
          <td>{{ $classroom->name }}</td>
        </tr>
        <tr>
          <td>Class Description</td>
          <td>{!! nl2br($classroom->description) !!}</td>
        </tr>
        <tr>
          <td>Class Room</td>
          <td>{{ Common::$rooms[$classroom->room] }}</td>
        </tr>
        <tr>
          <td>Teacher In Charge</td>
          <td>{{ Teacher::value('name')}}</td>
        </tr>
      </tbody>
    </table>
  </div>

@endsection